### ISSUE TITLE
[Feature REQUEST] Valheim First Person VR

### ISSUE THREAD

**Issue by ZanzyTHEbar** [Coopyy/ValheimFirstPerson#1]
Love your mod, i dabble in XR and VR developement, and wanted to work with you to create a port of your mod to enable Valheim in VR :) Valheim already has the XR and VR Unity dll and the /Managed folder - so with your mod as a base - we should be able to integrate the VR camerarig to the player head, put colliders on the arms with hand tracking and key binding to the VR controllers. I'd love to put some love into this- make this happen. Let me know

**Comment by Coopyy** [comment]
I really like the idea, unfortunately i sorta lost interest in the game pretty quick so im not planning on expanding this mod too much further, as it was intended as just a QOL mod for some friends and I. By all means you are welcome to use what anything here to do whatever you want. if you have any questions with the game i might be able to help with, my discord is `Coopyy#0001`. Ill look forward to seeing a vr mod if you do decide to go through with that :]

**Comment by ZanzyTHEbar** [comment]
That's a shame, i understand though. I did as well, i am hoping playing it in VR will renew my interest xD. I love VR, lol. It is a shame, simply because i am honestly useless when it comes to modding using BepInEx - i have no experience and i am not really sure where to begin modifying your code to integrate the Oculus and SteamVR SDK - or the OpenVR API ... Looking online, seems like a task for Sisyphus xD - but i'll muddle on through. Thank you for letting me have access to your code ) i'll credit you for anything i end up using. 

Do you have any suggestions on how i could begin? I went through your DLL using dnspy and dotPeek - not going to lie .... was a bit overwhelming. I would like to build this though - do you know anyone who might be interested,?

**Comment by Coopyy** [comment]
im not familiar with the modding scene for this game, so i havent heard of BepinEx until recently, but i do have experience with unity games so I didnt use any mod loader. Im sure it could be pretty easy to port over to that, just changing how the mod loads. I personally dont know anyone that even has a vr setup, but im sure if you posted it out there people would try it out. Again, feel free to ask any quesitons regarding anything you dont understand about my code, id be happy to help when i can
